# make a config yaml file

nustar-data-dir: "/disk/bifrost/nustar/fltops/"

sings-paths:
  main-dir: "/home/gaurav/sings/"
  essential-data-path: "/home/gaurav/sings/sings-products/essential-data/"
  gcn-db-path: "/home/gaurav/sings/sings-products/gcn-notices-sings.db"
  notice-archive-dir: "/home/gaurav/sings/sings-products/notices/"
  notices-log: "/home/gaurav/sings/sings-products/notices/notice-log.txt"
  ts-queue-db: "/home/gaurav/sings/sings-products/ts-queue.db"
  ts-products-dir: "/home/gaurav/sings/sings-products/ts-products/"
  
slack:
  slack-ts-reports: "sings-ts-reports"
  slack-ts-reports-id: "C0AFBGF5XRQ"
  slack-ts-reports-status: 0 # 0: off, 1: on
  slack-ts-notices: "sings-ts-notices"
  slack-ts-notices-id: "C0AEW3T775M"
  slack-ts-notices-status: 1 # 0: off, 1: on
  # slack-ts-circulars: "sings-ts-circulars" # put circulars in the same channel as notices for now
  # slack-ts-circulars-id: "C0AEW3T776M"
  # slack-ts-circulars-status: 0 # 0: off, 1: on
  slack-bs-reports: "sings-blind-reports"
  # slack-bs-reports-id: ""
  slack-bs-status: 0 # 0: off, 1: on

ts-config:
  ts-back-search: 1 # days to look back for TS products
  interval: 3600 # seconds between checks for new notices in the queue
